[gcp_service_account]
type = "service_account"
project_id = "alistounimar"
private_key_id = "188de5011d28184f23032ee14985e8158b62c95e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDsLJXv8SQkF++t
w57c1AFUwS8/gkVo4h4jctPniH9o7fVAL1ZVB5fZwghelBgaZTsAdrl0X9cmLClE
YXRV7NaJL5oW0KrJwL52M10JUxC2DJpJvkAHuAJJ4qzBxkF2ZOCwnpyhXL4eaIZM
/s/Je0Pcte4U9P0YcsIQDSPTjM62sIXYO6sbwvLChKFIbiMOEhCUGUcZpmQhPQkQ
FcDKp+u7rMj0do4cu9xBn3VwRfxh60UayKs+sSH3d+nWIZpsJxOhwTFI67uxAI6Q
M/orbX7tS0SHKvODJsqRmTluAlGtFp3l/U45KnapKcnLQuhM7GR4hOC2F+Tgu74F
5fZ2RajbAgMBAAECggEAVKhWxr+luNprq9nnZDkKkRr+mMFVqBcFvqc2llQzd6V0
uCE/zRL/t6r53Q0w5qVK1Qu5xqFkOeaylDRqwzI2ZM6PaYY68j8JBs26l9ESuG8k
DzMHOL0Y9OswCfXLGWlnsWfptV3NOJE3MvpT+WEaHk+InDKFVvIr5h0PrpFWt902
dKDy6Z6e7CranBrXEiW7GCcoXnimS4zswdP+C4WI9pOL6QjhIHmZwIxtOFponXcq
bDGm0C7FEZo6otqbdgvy48N5313IxF8vM1YkJA6euj17d23gbCP89mB6LB8hdI6l
e0sgmsUEQ/xAUENSbLUbVSqI6/9fK2ACQwftsCjcoQKBgQD/ZVpB/u0tnkxkhDsw
rVDvgrdh+60PTs9pn+18XIRJZ53Jh+aKjqXWfkLGdrbZCAYio262Qt6fEcndmjMi
Yi48qvoVFuStDDDjlktJ68e/X0V15ZUh9IdMYplYP3rE3YSLbFe0d7XwKIvSzDnQ
qS2D83PcPHBhmbfcEV2ddamsPQKBgQDsu5gOBs5ETgCheBOHIzKUH4Y+JvxfzedG
9yUsgUeL4O8FCm82D23q+dMu/PaQoYPB4RkmhlT14biM2ra8jeE0P4vPk/n6nODj
64KFVTGu5O/+cFCOidLfZ9MFLhRTibIhtdZKfVnb+FnrLYydltkpM7VeuJgXXSrg
kiCvOJgC9wKBgQCJ9utiGV9wtEHaTuBWtFmzeO6tnLJpQY6kJYO6GZRQvwuq0aJF
mTeW/k/+PCUcasw9rAHjrY3rakWdU25qFZWaqlY8TEit/pbuasMzJI6cH9A7FxGP
7TOlnOHvnSMp8+xlENr0H3MGUDDwZ+iXgryWuk4NXAztfIeo9yyWIfjNlQKBgQDj
q3aM5tawsiPBJm4BZURbWAYO+Ad3S9rFUSKbLqnUSLsWqfZSk3wuo50Kb5XherPw
Xb+GYWKMJk0Kib18kSaozQR02edrsjxGdlTMTia+AMceeH3A16PJ31v+e1ZpEOAT
s4Enmm41Mx+nIeM+G7k1+tjPA9Chh6SY3XA5k7/9+QKBgQDvDjvt9ACADKwoNezh
Wc78CKg3/Ha8sPJ+eKIUWzZviq/B6PcJsDpwDEkPciZ4vBYEP8f/XPQJDrB5rlVy
pibkCmu0R7LH5L/guy6gRVPI+O+ZZw6OlKBsNFT3FoHGmz6sjrKH20tZq+ahTcrT
tR/sHS0Y/S4mFnjP8x16Yrb4kA==
-----END PRIVATE KEY-----"""
client_email = "streamlit-registrador@alistounimar.iam.gserviceaccount.com"
client_id = "109827752142638688604"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-registrador%40alistounimar.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
